using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using USZ_ARTEMIS.Core.Rules;
using VMS.TPS.Common.Model.API;

namespace USZ_ARTEMIS.Actions
{
    partial class Rules
    {
        private static readonly string[] TemporaryRuleStructureIds =
        {
            "BodyHR_Ph",
            "RectalWallHelp_Ph"
        };

        private sealed class RuleMetadataPreparationPlan
        {
            public RuleMetadataPreparationPlan(
                StructureMetadataPreflightResult preflight,
                IEnumerable<string> additionalErrors)
            {
                Preflight = preflight;
                Errors = preflight.Errors.Concat(additionalErrors).ToList();
                Warnings = preflight.Warnings.ToList();
            }

            public StructureMetadataPreflightResult Preflight { get; }
            public IReadOnlyList<string> Errors { get; }
            public IReadOnlyList<string> Warnings { get; }
            public bool CanApply => Errors.Count == 0;
        }

        internal static bool AreSameStructureSet(
            StructureSet left,
            StructureSet right)
        {
            if (ReferenceEquals(left, right))
            {
                return true;
            }

            if (left == null || right == null)
            {
                return false;
            }

            return !string.IsNullOrWhiteSpace(left.UID) &&
                   !string.IsNullOrWhiteSpace(right.UID) &&
                   string.Equals(left.UID, right.UID, StringComparison.Ordinal);
        }

        private static RuleMetadataPreparationPlan BuildMetadataPreparationPlan(
            PlanRuleSet ruleSet,
            PlanSetup targetPlan,
            PlanSetup referencePlan,
            IEnumerable<Structure> structuresRemovedBeforeRules)
        {
            var structuresToRemove = structuresRemovedBeforeRules.ToList();
            var preflight = StructureMetadataPreflight.Evaluate(
                referencePlan.StructureSet.Structures.Select(CreateMetadataSnapshot),
                targetPlan.StructureSet.Structures.Select(CreateMetadataSnapshot),
                BuildOrderedRuleUses(ruleSet),
                structuresToRemove.Select(structure => structure.Id),
                TemporaryRuleStructureIds);

            var additionalErrors = new List<string>();
            foreach (Structure structure in structuresToRemove)
            {
                if (!targetPlan.StructureSet.CanRemoveStructure(structure))
                {
                    additionalErrors.Add(
                        $"Destination structure '{structure.Id}' must be regenerated by the rules " +
                        "but ESAPI reports that it cannot be removed.");
                }
            }

            return new RuleMetadataPreparationPlan(preflight, additionalErrors);
        }

        private static IEnumerable<RuleStructureUse> BuildOrderedRuleUses(
            PlanRuleSet ruleSet)
        {
            foreach (StructureRule rule in ruleSet.Rules ?? new List<StructureRule>())
            {
                var inputs = new List<string>(
                    rule.InputStructures ?? new List<string>());
                var outputs = new List<string>();

                if (rule.Type == RuleType.RectalWall)
                {
                    inputs.Add("BODY");
                    inputs.Add("Rectum");
                    outputs.Add("BodyHR_Ph");
                    outputs.Add("RectalWallHelp_Ph");
                    outputs.Add("RectalWall_Ph");
                }
                else if (rule.Type == RuleType.SbrtRing && inputs.Count == 2)
                {
                    outputs.Add(inputs[0] + "_Ph");
                }
                else if (!string.IsNullOrWhiteSpace(rule.OutputStructure))
                {
                    outputs.Add(rule.OutputStructure);
                }

                yield return new RuleStructureUse(inputs, outputs);
            }
        }

        private static StructureMetadataSnapshot CreateMetadataSnapshot(
            Structure structure)
        {
            StructureCode code = structure.StructureCode;
            return new StructureMetadataSnapshot(
                structure.Id,
                structure.DicomType,
                code?.CodingScheme,
                code?.Code,
                structure.IsApproved);
        }

        private static void PrepareRuleOutputStructures(
            StructureSet targetStructureSet,
            StructureSet referenceStructureSet,
            RuleMetadataPreparationPlan preparationPlan)
        {
            var referenceLookup = referenceStructureSet.Structures
                .Where(structure => !string.IsNullOrWhiteSpace(structure.Id))
                .ToDictionary(
                    structure => structure.Id.Trim(),
                    StringComparer.OrdinalIgnoreCase);

            foreach (StructureMetadataPreparation preparation in
                     preparationPlan.Preflight.Preparations)
            {
                Structure target = FindExistingStructure(
                    targetStructureSet,
                    preparation.StructureId);

                if (preparation.Kind ==
                    StructureMetadataPreparationKind.CreateFromReference ||
                    preparation.Kind ==
                    StructureMetadataPreparationKind.CreateTemporary)
                {
                    if (target != null)
                    {
                        throw new InvalidOperationException(
                            $"Structure '{preparation.StructureId}' still exists after the " +
                            "metadata preflight marked it for creation.");
                    }

                    if (!targetStructureSet.CanAddStructure(
                            preparation.ExpectedVolumeType,
                            preparation.StructureId))
                    {
                        throw new InvalidOperationException(
                            $"ESAPI cannot create structure '{preparation.StructureId}' with " +
                            $"Volume Type '{preparation.ExpectedVolumeType}'.");
                    }

                    target = targetStructureSet.AddStructure(
                        preparation.ExpectedVolumeType,
                        preparation.StructureId);
                }

                if (target == null)
                {
                    throw new InvalidOperationException(
                        $"Structure '{preparation.StructureId}' was not available after preparation.");
                }

                if (preparation.Kind ==
                    StructureMetadataPreparationKind.CreateTemporary)
                {
                    VerifyVolumeType(target, preparation.ExpectedVolumeType);
                    continue;
                }

                if (!referenceLookup.TryGetValue(
                        preparation.StructureId.Trim(),
                        out Structure reference))
                {
                    throw new InvalidOperationException(
                        $"The base-plan structure '{preparation.StructureId}' disappeared after " +
                        "metadata preflight.");
                }

                VerifyVolumeType(target, reference.DicomType);

                if (!StructureCodesEqual(target.StructureCode, reference.StructureCode))
                {
                    target.StructureCode = reference.StructureCode;
                }

                if (!StructureCodesEqual(target.StructureCode, reference.StructureCode))
                {
                    throw new InvalidOperationException(
                        $"Structure Code synchronization failed for '{preparation.StructureId}'.");
                }
            }
        }

        private static void VerifyRuleOutputMetadata(
            PlanRuleSet ruleSet,
            StructureSet targetStructureSet,
            StructureSet referenceStructureSet)
        {
            var temporaryIds = new HashSet<string>(
                TemporaryRuleStructureIds,
                StringComparer.OrdinalIgnoreCase);
            var referenceLookup = referenceStructureSet.Structures
                .Where(structure => !string.IsNullOrWhiteSpace(structure.Id))
                .ToDictionary(
                    structure => structure.Id.Trim(),
                    StringComparer.OrdinalIgnoreCase);
            var outputIds = BuildOrderedRuleUses(ruleSet)
                .SelectMany(ruleUse => ruleUse.OutputIds)
                .Where(id => !string.IsNullOrWhiteSpace(id))
                .Select(id => id.Trim())
                .Where(id => !temporaryIds.Contains(id))
                .Distinct(StringComparer.OrdinalIgnoreCase);
            var errors = new List<string>();

            foreach (string outputId in outputIds)
            {
                Structure target = FindExistingStructure(
                    targetStructureSet,
                    outputId);
                if (target == null)
                {
                    errors.Add($"Rule output '{outputId}' is missing after rule application.");
                    continue;
                }

                if (!referenceLookup.TryGetValue(outputId, out Structure reference))
                {
                    errors.Add(
                        $"Rule output '{outputId}' no longer has a matching base-plan structure.");
                    continue;
                }

                if (!string.Equals(
                        target.DicomType,
                        reference.DicomType,
                        StringComparison.OrdinalIgnoreCase))
                {
                    errors.Add(
                        $"Volume Type mismatch for '{outputId}': base='{reference.DicomType}', " +
                        $"destination='{target.DicomType}'.");
                }

                if (!StructureCodesEqual(target.StructureCode, reference.StructureCode))
                {
                    errors.Add($"Structure Code mismatch for '{outputId}'.");
                }
            }

            if (errors.Count > 0)
            {
                throw new InvalidOperationException(
                    "Structure metadata verification failed:\n- " +
                    string.Join("\n- ", errors));
            }
        }

        private static Structure FindExistingStructure(
            StructureSet structureSet,
            string structureId)
        {
            return structureSet.Structures.FirstOrDefault(
                structure =>
                    !string.IsNullOrWhiteSpace(structure.Id) &&
                    structure.Id.Trim().Equals(
                        structureId.Trim(),
                        StringComparison.OrdinalIgnoreCase));
        }

        private static void VerifyVolumeType(
            Structure structure,
            string expectedVolumeType)
        {
            if (!string.Equals(
                    structure.DicomType,
                    expectedVolumeType,
                    StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException(
                    $"Volume Type verification failed for '{structure.Id}': " +
                    $"expected='{expectedVolumeType}', actual='{structure.DicomType}'.");
            }
        }

        private static bool StructureCodesEqual(
            StructureCode left,
            StructureCode right)
        {
            if (ReferenceEquals(left, right))
            {
                return true;
            }

            if (left == null || right == null)
            {
                return false;
            }

            return string.Equals(
                       left.CodingScheme,
                       right.CodingScheme,
                       StringComparison.Ordinal) &&
                   string.Equals(
                       left.Code,
                       right.Code,
                       StringComparison.Ordinal);
        }

        private static string FormatMetadataPreflightFailure(
            RuleMetadataPreparationPlan plan)
        {
            var message = new StringBuilder();
            message.AppendLine("Structure metadata preflight failed.");
            message.AppendLine();

            foreach (string error in plan.Errors)
            {
                message.AppendLine("- " + error);
            }

            message.AppendLine();
            message.Append(
                "No rules were applied. Correct the destination structure set or the base-plan " +
                "rules before trying the plan copy again.");
            return message.ToString();
        }
    }
}
